language: generic
dist: bionic
install:
- source ./texlive/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR/
script:
- xelatex praca.tex
- bibtex praca.aux
- xelatex praca.tex
- xelatex praca.tex
deploy:
  provider: releases
  api_key:
    secure: La+w6gMnzZp/L8o6e3Gjj0WCutBUbQ7mjKA80KBF6d9hXpcycQNeFlOl3pj7pcJ+XdBhrztXysVTgj9nEWRu84hP02zaWRxXkXLtrjpJb1U9+LMycew5Uwbywx2miDaVKlXwnrZspY3Sv2hLFbMfVX74W7aFOBoZz/jpSXR3AyvBrtRAXfA60Ah3JR4YDNZZQC+nWDNUXJEqBQSecsMN1KJ9BYOFFQv4fW9h4kY/eLASyMfKSwwThYn7Djf8AYlTiwIzy3Us4EIJDvuQO5/xs5wTi0nB0LSP9/gnRkPou9JvJp5qNFXLPDqIqyUf4w1T6DII8eitn6frwpB1nwYjLkp27Kc/Lff5lEQMlfxLCMRCUqiqk2gj/XfUSeMsqhyl50rG+NkEC71oeiLFnaoEz6eK1+oJaiB2GH/efV8xM5v1lafbtQC7mL1xqiWn+WwiQ8j05KcfY3jSmSxUnsth3G+Y45B7AH3NTJHwk+E8sJXoPgi3kzEWBI9nxHpyZaIy1cR52fETZVsnLnugoXTJdPRsymnvkmbIJmmeCxW0TxZsrg5KhcpqYOA8NjgbFRe+zy7JjQI2rJJa5CrHYjTgITMR3vgOzq8koRANfniushNoKNPDh3S0FJI6I1v3iOW2r4gO/Kvj3koy28TTCmy/KPzAFhvKG8QFmD5I0glw68Y=
  file: praca.pdf
  skip_cleanup: true
  on:
    #tags: true
    branch: master
